// English-only, permanently (the public site's 16-language i18n system
// was removed entirely in the v25 redesign) -- every user-facing string
// still lives in this one namespaced object, keyed in dot-path-able
// sections, so copy is never hunted down inline across the app. Do not
// put user-facing copy directly in a component -- add it here and
// import it instead.
export const strings = {
  app: {
    name: "Care Hub",
    brand: "Little Technical Solutions",
  },
  nav: {
    dashboard: "Dashboard",
    tickets: "Tickets",
    checklists: "Readiness Checklists",
    scopeOfWork: "Scope of Work",
    changeOrders: "Change Orders",
    approvals: "Approvals",
    organizations: "Organizations",
    reminders: "Reminders",
    serviceRecords: "Service Records",
    websiteProfiles: "Website Profiles",
    subscriptions: "Subscriptions",
    technologyAssets: "Technology Assets",
    entitlements: "Entitlements",
    templates: "Templates",
    metrics: "Metrics",
    auditLog: "Audit Log",
    activityTimeline: "Activity Timeline",
    itSupport: "IT Support",
    workLog: "Work Log",
    account: "Account",
    signOut: "Sign out",
    groupWork: "Work",
    groupAccountBilling: "Account & Billing",
    groupAdmin: "Admin",
    project: "Project",
    yourWebsite: "Your Website",
    billing: "Billing",
    siteContent: "Site Content",
    imageLibrary: "Image Library",
    customerSupport: "Customer Support",
  },
  overview: {
    shortcutsHeading: "Get things done",
    activityHeading: "Recent activity",
    activityEmptyBody: "Nothing has happened on your account yet. Updates will show up here as work progresses.",
    activitySeeAll: "See all activity",
    ticketsShortcutBody: "Submit a request or check on an open ticket.",
    checklistsShortcutBody: "Answer your site-readiness checklist.",
    approvalsShortcutBody: "Review anything waiting on your decision.",
    projectShortcutBody: "See your current scope and any proposed changes.",
    yourWebsiteShortcutBody: "Site details, technology, and service history.",
    billingShortcutBody: "Your plan, usage, and subscription status.",
  },
  projectHub: {
    title: "Project",
    intro: "The agreed scope for your project, and anything proposed since.",
    scopeOfWorkBody: "The current agreed-upon scope of work, and its version history.",
    changeOrdersBody: "Additional work proposed beyond the original scope.",
  },
  yourWebsiteHub: {
    title: "Your Website",
    intro: "Everything on file about your site, its technology, and past service.",
    websiteProfilesBody: "Domain, hosting, and site details on file.",
    technologyAssetsBody: "Technology assets and backup history.",
    serviceRecordsBody: "A record of service work on your account.",
    remindersBody: "Upcoming domain, SSL, warranty, and license expirations.",
  },
  billingHub: {
    title: "Billing",
    intro: "Your subscription and current plan usage.",
    subscriptionsBody: "Plan status and billing history.",
    entitlementsBody: "What your current plan includes, and how much you've used.",
  },
  states: {
    loading: "Loading…",
    emptyTitle: "Nothing here yet",
    emptyBody: "There's nothing to show for this view right now.",
    errorTitle: "Something went wrong",
    errorBody: "We couldn't complete that request. Try again, and contact us if it keeps happening.",
    retry: "Try again",
    unauthorizedTitle: "You don't have access to this",
    unauthorizedBody: "Your account doesn't have permission to view this page. If you think this is a mistake, contact us.",
    sessionExpiredTitle: "Your session has expired",
    sessionExpiredBody: "For your security, you've been signed out. Please sign in again to continue.",
    signInAgain: "Sign in again",
    notFoundTitle: "Page not found",
    notFoundBody: "That page doesn't exist, or you may not have access to it.",
  },
  auth: {
    loginTitle: "Sign in",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    invalidCredentials: "Incorrect email or password.",
    mfaCodeTitle: "Enter your authenticator code",
    mfaCodeLabel: "6-digit code",
    mfaVerifyButton: "Verify",
    mfaVerifying: "Verifying…",
    mfaRecoveryLabel: "Recovery code",
    mfaUseRecoveryCode: "Use a recovery code instead",
    mfaUseAuthenticatorCode: "Use your authenticator app instead",
    mfaIncorrectCode: "That code didn't work. Try again.",
    mfaEnrollTitle: "Set up two-factor authentication",
    mfaEnrollBody: "Administrator accounts require an authenticator app (Google Authenticator, 1Password, Authy, etc.). Add this account using the key below, then enter the 6-digit code it generates to confirm.",
    mfaEnrollManualKeyLabel: "Manual entry key",
    mfaEnrollConfirmButton: "Confirm and enable",
    mfaEnrollConfirming: "Confirming…",
    mfaRecoveryCodesTitle: "Save your recovery codes",
    mfaRecoveryCodesBody: "Store these somewhere safe. Each code works once, and they will not be shown again. Use one if you ever lose access to your authenticator app.",
    mfaRecoveryCodesContinue: "I've saved these, continue",
    noPendingSignIn: "Your sign-in session expired before you finished. Please sign in again.",
    mfaCheckEmailTitle: "Check your email to finish setup",
    mfaCheckEmailBody: "We sent a confirmation link to your email. Click it within 30 minutes to finish enabling two-factor authentication. If you don't see it, check your spam folder or contact us.",
    mfaEmailConfirmTitle: "Confirm two-factor authentication",
    mfaEmailConfirmBody: "Only continue if you just requested this change. Confirming will enable two-factor authentication and sign you in.",
    mfaEmailConfirmButton: "Confirm and enable",
    mfaEmailMissingToken: "This confirmation link is missing its token.",
    mfaEmailInvalid: "This confirmation link is invalid or has expired.",
    forgotPassword: "Forgot password?",
  },
  resetPassword: {
    requestTitle: "Reset your password",
    emailLabel: "Email",
    sendButton: "Send reset link",
    sending: "Sending…",
    requestSentBody: "If that email is registered, a reset link has been sent. Check your inbox (and spam folder), then come back and follow the link.",
    backToSignIn: "Back to sign in",
    confirmTitle: "Set a new password",
    newPasswordLabel: "New password (at least 10 characters)",
    updateButton: "Update password",
    updating: "Updating…",
    genericError: "Something went wrong. Try again, or contact us if it keeps happening.",
    doneTitle: "Password updated",
    doneBody: "Sign in below with your new password.",
    goToSignIn: "Go to sign in",
  },
  invite: {
    loading: "Checking your invitation…",
    invalidTitle: "This invitation link isn't valid",
    invalidBody: "It may have already been used, revoked, or expired. Contact us if you think this is a mistake.",
    introPrefix: "You've been invited to join",
    introSuffix: "on the Care Hub as",
    nameLabel: "Your name",
    passwordLabel: "Choose a password (at least 10 characters)",
    termsRequired: "You must agree to the Terms of Service and acknowledge the Privacy Policy to continue.",
    marketingLabel: "Send me occasional updates and offers (optional).",
    submitButton: "Create account",
    submitting: "Creating account…",
    doneTitle: "Account created",
    doneBody: "Sign in below with the password you just set.",
    goToSignIn: "Go to sign in",
    genericError: "Something went wrong. Try again, or contact us if it keeps happening.",
  },
  tickets: {
    title: "Tickets",
    newTicket: "New ticket",
    cancel: "Cancel",
    category: "Category",
    subject: "Subject",
    description: "Description",
    submit: "Submit request",
    submitting: "Submitting…",
    categoryLabels: {
      website_change: "Website change",
      it_support: "IT support",
      question: "Question",
      other: "Other",
    },
    staffNotAvailableTitle: "No organization to show",
    staffNotAvailableBody: "Staff ticket management across every organization isn't built in this screen yet -- this view is for a signed-in customer's own tickets.",
    emptyTitle: "No tickets yet",
    emptyBody: "Submit a request and it will show up here.",
    submittedBy: "Submitted",
    workQueueTitle: "Open tickets (all organizations)",
    workQueueEmptyTitle: "No open tickets",
    workQueueEmptyBody: "Nothing in the queue right now.",
    organizationLabel: "Organization",
    priorityLabels: { critical: "Critical", high: "High", medium: "Medium", low: "Low" },
    statusLabel: "Status",
    transitionButton: "Update status",
    transitioning: "Updating…",
  },
  checklists: {
    title: "Readiness Checklists",
    submitForReview: "Submit for review",
    submitting: "Submitting…",
    statusLabels: {
      draft: "Draft",
      submitted: "Submitted for review",
      returned: "Returned for changes",
      verified: "Verified",
    },
    returnedNoteLabel: "Staff feedback",
    metLabel: "Yes",
    unmetLabel: "No",
    commentLabel: "Comment (optional)",
    saveAnswer: "Save",
    saving: "Saving…",
    reviewedByStaff: "This checklist has been verified by staff.",
    underReviewNotice: "Submitted for review -- staff will verify or return this checklist. You can't make changes right now.",
    noChecklistTitle: "No checklist assigned yet",
    noChecklistBody: "Your organization doesn't have a readiness checklist to complete yet.",
    staffOrgPickerLabel: "Organization ID",
    staffOrgPickerHelp: "Enter the customer organization's ID to review their checklist. (There's no organization directory screen yet -- paste the ID from Netlify Blobs/Neon or a customer record.)",
    staffLoadButton: "Load",
    staffVerifiedLabel: "Staff verified",
    staffNoteLabel: "Internal note (staff only)",
    staffAnswerLabel: "Staff answer",
    saveAssessment: "Save assessment",
    savingAssessment: "Saving…",
    returnForChanges: "Return for changes",
    returnReasonLabel: "What needs to change?",
    returnButton: "Send back to customer",
    verifyButton: "Mark verified",
    reviewing: "Working…",
    scoreLabel: "Score",
    audienceLabels: { customer: "Customer", staff: "Staff" },
  },
  scopeOfWork: {
    title: "Scope of Work",
    ticketPickerLabel: "Ticket",
    noTicketsTitle: "No tickets yet",
    noTicketsBody: "Scope of work is tied to a ticket -- submit one first.",
    noScopeBody: "No scope of work has been drafted for this ticket yet.",
    versionLabel: (version: number) => `Version ${version}`,
    statusLabels: { draft: "Draft", sent: "Sent", superseded: "Superseded" },
    currentBadge: "current",
    assumptionsLabel: "Assumptions",
    exclusionsLabel: "Exclusions",
    newScopeHeading: "Draft the initial scope",
    newVersionHeading: "Create a new version",
    lineItemDescriptionLabel: "Description",
    lineItemQuantityLabel: "Quantity",
    lineItemPriceRefLabel: "Price reference",
    addLineItem: "Add line item",
    assumptionsFieldLabel: "Assumptions (one per line, optional)",
    exclusionsFieldLabel: "Exclusions (one per line, optional)",
    saving: "Saving…",
    createScope: "Create scope",
    saveNewVersion: "Save new version",
  },
  changeOrders: {
    title: "Change Orders",
    noChangeOrdersBody: "Change orders show up here when additional work is proposed beyond the original scope.",
    approvalHint: "Change orders are approved or rejected by your organization's owner from the Approvals page.",
    newHeading: "Create a change order",
    noCurrentScopeBody: "This ticket doesn't have a current scope of work to attach a change order to yet.",
    descriptionLabel: "What's changing",
    addedLineItemsHeading: "Additional line items",
    originalScopeLabel: (version: number) => `Against scope version ${version}`,
    creating: "Creating…",
    createButton: "Create change order",
  },
  approvals: {
    title: "Approvals",
    emptyBody: "There's nothing waiting on your approval right now.",
    staffNotApplicableTitle: "Not shown to staff accounts",
    staffNotApplicableBody: "Approvals are decided by the organization owner, or by a platform administrator on their behalf -- technician accounts don't see this inbox.",
    subjectTypeLabels: { scope: "Scope of work", change_order: "Change order", deliverable: "Deliverable", document: "Document" },
    statusLabels: { pending: "Pending", approved: "Approved", rejected: "Rejected", expired: "Expired" },
    requestedLabel: "Requested",
    expiresLabel: "expires",
    decisionNoteLabel: "Note",
    decisionNoteFieldLabel: "Note (optional)",
    approveButton: "Approve",
    rejectButton: "Reject",
    deciding: "Saving…",
  },
  organizations: {
    title: "Organizations",
    notAvailableTitle: "Not available on your account",
    notAvailableBody: "Organization and invitation management is limited to platform administrator accounts.",
    createHeading: "Create a new organization",
    nameLabel: "Organization name",
    createButton: "Create organization",
    creating: "Creating…",
    lookupHeading: "Look up an organization",
    lookingUp: "Loading…",
    idLabel: "Organization ID",
    statusLabel: "Status",
    statusLabels: { active: "Active", suspended: "Suspended", archived: "Archived" },
    createdAtLabel: "Created",
    versionLabel: "Version",
    updateStatusButton: "Update status",
    updatingStatus: "Updating…",
    invitationsHeading: "Invitations",
    noInvitationsBody: "No invitations sent yet for this organization.",
    inviteHeading: "Send an invitation",
    inviteEmailLabel: "Email",
    inviteRoleLabel: "Role",
    invitationRoleLabels: {
      org_owner: "Organization owner",
      org_member: "Organization member",
      read_only_customer: "Read-only customer",
    },
    inviteButton: "Send invitation",
    inviting: "Sending…",
    invitationStatusLabels: { pending: "Pending", accepted: "Accepted", revoked: "Revoked", expired: "Expired" },
    invitedLabel: "Invited",
    expiresLabel: "Expires",
    resendCountLabel: "Resent",
    resendButton: "Resend",
    resending: "Resending…",
    revokeButton: "Revoke",
    revoking: "Revoking…",
  },
  reminders: {
    title: "Reminders",
    emptyTitle: "No reminders yet",
    emptyBody: "There are no upcoming expirations to show for this organization.",
    expiresAtLabel: "Expires",
    sentBadge: "Sent",
    newHeading: "Create a reminder",
    subjectIdFieldLabel: "Subject",
    subjectIdFieldPlaceholder: "e.g. lit-solutions.tech, or an asset ID",
    subjectTypeFieldLabel: "Type",
    subjectTypeFieldPlaceholder: "e.g. domain, ssl, warranty, license, subscription",
    expiresAtFieldLabel: "Expires on",
    creating: "Creating…",
    createButton: "Create reminder",
  },
  serviceRecords: {
    title: "Service Records",
    emptyTitle: "No service records yet",
    emptyBody: "Service records for this organization will show up here.",
    categoryLabel: "Category",
    categoryLabels: {
      website: "Website",
      it: "IT",
      security: "Security",
      recurring_service: "Recurring service",
    },
    statusLabel: "Status",
    statusLabels: {
      active: "Active",
      on_hold: "On hold",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    createdLabel: "Created",
    newHeading: "Create a service record",
    titleFieldLabel: "Title",
    creating: "Creating…",
    createButton: "Create record",
    transitionButton: "Update status",
    transitioning: "Updating…",
  },
  websiteProfiles: {
    title: "Website Profiles",
    emptyTitle: "No website profiles yet",
    emptyBody: "Website profiles for this organization will show up here.",
    domainRegistrarLabel: "Domain registrar",
    hostingProviderLabel: "Hosting provider",
    newHeading: "Create a website profile",
    primaryUrlFieldLabel: "Website URL",
    domainRegistrarFieldLabel: "Domain registrar (optional)",
    hostingProviderFieldLabel: "Hosting provider (optional)",
    creating: "Creating…",
    createButton: "Create profile",
    editButton: "Edit",
    saveButton: "Save",
    cancelButton: "Cancel",
    saving: "Saving…",
  },
  subscriptions: {
    title: "Subscriptions",
    emptyBody: "No subscriptions have been set up for this organization yet.",
    statusLabels: { active: "Active", paused: "Paused", cancelled: "Cancelled" },
    statusLabel: "Status",
    startedLabel: "Started",
    pausedLabel: "Paused",
    cancelledLabel: "Cancelled",
    transitionButton: "Update status",
    transitioning: "Updating…",
    newHeading: "Create a subscription",
    planKeyLabel: "Plan key",
    createButton: "Create subscription",
    creating: "Creating…",
  },
  technologyAssets: {
    title: "Technology Assets",
    emptyBody: "No technology assets have been recorded for this organization yet.",
    warrantyLabel: "Warranty expires",
    licenseLabel: "License expires",
    newAssetHeading: "Add a technology asset",
    typeLabel: "Type",
    labelLabel: "Label",
    warrantyFieldLabel: "Warranty expires (optional)",
    licenseFieldLabel: "License expires (optional)",
    createAssetButton: "Add asset",
    creatingAsset: "Adding…",
    backupsHeading: "Backups",
    websiteProfileIdLabel: "Website profile ID",
    categoryLabel: "Category",
    categoryLabels: {
      source: "Source",
      content: "Content",
      assets: "Assets",
      database: "Database",
      configuration: "Configuration",
    },
    locationLabel: "Location",
    recordBackupButton: "Record backup",
    recordingBackup: "Recording…",
    takenAtLabel: "Taken",
    restoreVerifiedLabel: "Restore verified",
    restoreNotVerifiedLabel: "Restore not yet verified",
    verifyBackupButton: "Mark restore-verified",
    verifyingBackup: "Verifying…",
  },
  entitlements: {
    title: "Entitlements",
    overviewHeading: "Current plan usage",
    noActiveSubscriptionBody:
      "No active subscription found for this organization -- once one exists, its usage will show here automatically.",
    noLimitsConfiguredBody: "This plan doesn't have any usage limits configured yet.",
    lookupHeading: "Manual lookup",
    lookupHelp:
      "Use this to check a specific plan key and usage key directly -- useful for a plan not tied to this organization's current subscription, or a usage key not shown in the usage overview above.",
    planKeyLabel: "Plan key",
    usageKeyLabel: "Usage key",
    checkUsageButton: "Check usage",
    checking: "Checking…",
    limitLabel: "Limit",
    consumedLabel: "Used",
    remainingLabel: "Remaining",
    periodStartLabel: "Period started",
    resetPeriodLabel: "Resets",
    resetPeriodLabels: { monthly: "Monthly", total: "Total (does not reset)", unlimited: "Unlimited" },
    unlimitedLabel: "Unlimited",
    recordUsageHeading: "Record usage",
    amountLabel: "Amount",
    recordUsageButton: "Record usage",
    recording: "Recording…",
    recordedLabel: "Recorded",
    withinLimitLabel: "Within limit",
    yesLabel: "Yes",
    noLabel: "No",
  },
  templates: {
    title: "Templates",
    notPlatformAdminTitle: "Not available for this account",
    notPlatformAdminBody:
      "Notification templates are managed by platform administrators only. If you believe this is a mistake, contact us.",
    createHeading: "Create a template",
    keyLabel: "Key",
    subjectLabel: "Subject",
    bodyLabel: "Body",
    allowedVariablesLabel: "Allowed variables (comma-separated)",
    allowedVariablesHelp:
      "e.g. customerName, ticketSubject -- these are the only variable names the render/preview form below will accept for this template.",
    createButton: "Create template",
    creating: "Creating…",
    createdHeading: "Existing templates",
    createdEmptyBody: "No templates have been created yet. Templates you create above will appear here.",
    variablesLabel: "Variables",
    renderHeading: "Render / preview a template",
    renderHelp:
      "Choose an existing template to render it with sample values -- its allowed variables fill in automatically. If no templates have been created yet, enter a key manually.",
    renderKeyLabel: "Template key",
    renderKeyPlaceholder: "Select a template…",
    variableNameLabel: "Variable name",
    variableValueLabel: "Variable value",
    addVariable: "Add variable",
    renderButton: "Render template",
    rendering: "Rendering…",
    renderedSubjectLabel: "Rendered subject",
    renderedBodyLabel: "Rendered body",
  },
  siteContent: {
    title: "Site Content",
    notPlatformAdminTitle: "Not available for this account",
    notPlatformAdminBody: "Site content is managed by platform administrator accounts only.",
    addNewHeading: "Add new",
    editItemHeading: "Edit item",
    addButton: "Add item",
    updateButton: "Update item",
    cancelEditButton: "Cancel edit",
    currentItemsHeading: "Current items",
    currentItemsNote: "Every change below (adding, editing, deleting, or reordering) saves and goes live on the site immediately.",
    emptyBody: "Nothing here yet.",
    moveUp: "Move up",
    moveDown: "Move down",
    editButton: "Edit",
    deleteButton: "Delete",
    savingStatus: "Saving…",
    savedStatus: "✓ — live on the site now.",
    deletedStatus: "Deleted ✓ — removed from the site.",
    reorderedStatus: "Order saved ✓ — live on the site now.",
    saveErrorFallback: "Could not save — this change hasn't gone live. Check your connection and try again.",
    missingFieldsPrefix: "Please fill in: ",
    deleteConfirm: (label: string) => `Delete "${label}"? This removes it from the live site right away.`,
    removePhotoButton: "Remove photo",
    imageTooLarge: "Please use an image under about 3.5MB.",
  },
  imageLibrary: {
    title: "Image Library",
    notPlatformAdminTitle: "Not available for this account",
    notPlatformAdminBody: "The image library is managed by platform administrator accounts only.",
    intro: "Photos you've uploaded, for reference. To use one on a post or portfolio item, upload it directly in that item's form instead -- this list is just for keeping track of what's here.",
    uploadHeading: "Upload an image",
    altLabel: "Alt text",
    uploadButton: "Upload",
    uploading: "Uploading…",
    uploadedStatus: "Uploaded ✓",
    deletedStatus: "Deleted ✓",
    deletingStatus: "Deleting…",
    emptyBody: "No images uploaded yet.",
    noAltText: "(no alt text)",
    uploadedLabel: "Uploaded",
    deleteConfirm: "Delete this image? Posts/items already using it will keep their own copy.",
    chooseFileFirst: "Choose a file first.",
    imageTooLarge: "Please use an image under about 3.5MB.",
    uploadErrorFallback: "Upload failed -- check your connection and try again.",
    deleteErrorFallback: "Could not delete -- check your connection and try again.",
  },
  customerSupport: {
    title: "Customer Support",
    notPlatformAdminTitle: "Not available for this account",
    notPlatformAdminBody: "Customer support tools are managed by platform administrator accounts only.",
    inboxHeading: "Customer inbox",
    inboxIntro: "Customers with an open conversation, newest first.",
    inboxEmptyBody: "No conversations yet.",
    inboxLoadError: "Could not load the inbox.",
    openButton: "Open",
    unreadSuffix: (count: number) => `(${count} unread)`,
    lookupHeading: "Look up a customer",
    lookupIntro: "Enter the email a customer registered with to see (and add to) their documents and messages. They can only see their own -- there's no way for one customer to see another's records or messages.",
    lookupEmailLabel: "Customer email",
    lookupButton: "Look up customer",
    lookupNotFound: "Could not find that customer.",
    lookupFound: (name: string, email: string) => `Found: ${name} (${email})`,
    messagesHeadingFor: (name: string) => `Messages with ${name}`,
    noMessagesYet: "No messages yet.",
    replyLabel: "Reply",
    sendReplyButton: "Send reply",
    sending: "Sending…",
    typeMessageFirst: "Type a message first.",
    lookupCustomerFirst: "Look up a customer first.",
    notificationHeading: "Send a notification",
    notificationIntro: 'A one-way alert that shows up in this customer\'s account (separate from a message -- use this for things like "your appointment was rescheduled" that don\'t need a reply).',
    notificationTitleLabel: "Title",
    notificationTitlePlaceholder: "e.g. Appointment rescheduled",
    notificationDetailsLabel: "Details (optional)",
    notificationSendButton: "Send notification",
    notificationTitleRequired: "Title is required.",
    notificationSent: "Sent.",
    notificationErrorFallback: "Could not send.",
    documentUploadHeadingFor: (name: string) => `Upload a document for ${name}`,
    documentListHeadingFor: (name: string) => `${name}'s documents`,
    documentTitleLabel: "Title",
    documentTypeLabel: "Type",
    documentTypeLabels: { invoice: "Invoice", receipt: "Receipt", paperwork: "Paperwork", other: "Other" },
    documentAmountLabel: "Amount (optional, e.g. $150.00)",
    documentStatusLabel: "Status",
    documentStatusLabels: { "n/a": "N/A", unpaid: "Unpaid", paid: "Paid" },
    documentDateLabel: "Date",
    documentNotesLabel: "Notes (optional)",
    documentFileLabel: "Attachment (optional, PDF or image, under ~3.5MB)",
    documentUploadButton: "Upload for this customer",
    documentUploading: "Uploading…",
    documentUploaded: "Uploaded.",
    documentUploadErrorFallback: "Could not upload.",
    documentTitleRequired: "Title is required.",
    documentEmptyBody: "No documents uploaded for this customer yet.",
    documentDeleteConfirm: (title: string) => `Delete "${title}"? This can't be undone.`,
    documentDeleteButton: "Delete",
    fileTooLarge: "Please use a file under about 3.5MB.",
    messageThreadYou: "You",
    messageErrorFallback: "Could not send.",
  },
  metrics: {
    title: "Metrics",
    notPlatformAdminTitle: "Not available for this account",
    notPlatformAdminBody: "Operational metrics are only available to platform administrator accounts.",
    fromLabel: "From",
    toLabel: "To",
    submitButton: "Get summary",
    submitting: "Loading…",
    emptyBody: "No events recorded for that date range.",
    byTypeHeading: "Events by type",
    byDayHeading: "Events by day",
    typeColumnLabel: "Type",
    dayColumnLabel: "Date",
    countColumnLabel: "Count",
  },
  auditLog: {
    title: "Audit Log",
    notPlatformAdminTitle: "Not available for this account",
    notPlatformAdminBody: "The audit log is only available to platform administrator accounts.",
    organizationIdLabel: "Organization ID",
    actorIdLabel: "Actor ID",
    actionLabel: "Action",
    dateFromLabel: "From",
    dateToLabel: "To",
    searchButton: "Search",
    searching: "Searching…",
    emptyBody: "No matching audit events.",
    occurredAtColumnLabel: "Occurred",
    actorColumnLabel: "Actor",
    actionColumnLabel: "Action",
    targetColumnLabel: "Target",
    organizationColumnLabel: "Organization",
    outcomeColumnLabel: "Outcome",
    actorTypeLabels: { user: "User", automated_service: "Automated service", system: "System" },
    outcomeLabels: { success: "Success", failure: "Failure", denied: "Denied" },
    loadMore: "Load more",
    loadingMore: "Loading…",
  },
  activityTimeline: {
    title: "Activity Timeline",
    staffNotApplicableTitle: "Not shown to staff accounts",
    staffNotApplicableBody:
      "The activity timeline is a customer-facing view of your account's history -- technician and platform admin accounts use the work queue instead.",
    emptyBody: "Nothing has happened on your account yet. Updates will show up here as work progresses.",
  },
  itSupport: {
    title: "IT Support Classification",
    customerNotApplicableTitle: "Not shown to customer accounts",
    customerNotApplicableBody:
      "IT support classification is an internal staff tool for deciding how a ticket gets handled -- customer accounts don't see this screen.",
    classifyHeading: "Classify this ticket",
    requiresPhysicalAccessLabel: "Requires physical access",
    safetyRiskLabel: "Safety risk involved",
    submitButton: "Classify",
    submitting: "Classifying…",
    resultHeading: "Classification result",
    classificationLabels: { remote: "Remote", on_site: "On-site", escalate: "Escalate" },
    reasonLabel: "Reason",
  },
  workLog: {
    title: "Work Log",
    customerNotApplicableTitle: "Not shown to customer accounts",
    customerNotApplicableBody:
      "Work log time entries and internal notes are an internal staff tool -- customer accounts don't see this screen.",
    totalHeading: "Time logged",
    totalMinutesLabel: (minutes: number) => `${minutes} minutes`,
    logTimeHeading: "Log time",
    minutesLabel: "Minutes",
    timeNoteLabel: "Note (optional)",
    logButton: "Log time",
    logging: "Logging…",
    addNoteHeading: "Add an internal note",
    noteBodyLabel: "Note",
    addNoteButton: "Add note",
    addingNote: "Adding…",
    noteSaved: "Note added.",
  },
  account: {
    signedInAs: "Signed in as",
    nameHeading: "Your name",
    nameLabel: "Name",
    nameSubmit: "Update name",
    emailHeading: "Change email",
    newEmailLabel: "New email",
    currentPasswordLabel: "Current password",
    emailSubmit: "Update email",
    passwordHeading: "Change password",
    newPasswordLabel: "New password (at least 10 characters)",
    passwordSubmit: "Update password",
    signOutNotice: "For your security, that signs you out everywhere -- sign in again with your new credentials.",
    preferencesHeading: "Preferences",
    timezoneLabel: "Timezone (optional)",
    emailNotificationsLabel: "Email me about new tickets, checklist updates, and messages",
    preferencesSubmit: "Save preferences",
    mfaHeading: "Two-factor authentication",
    mfaBody: "Two-factor authentication is required for administrator accounts and can't be turned off, but you can reset it (useful if you've lost your authenticator app) by confirming your password below.",
    mfaPasswordLabel: "Current password",
    mfaResetButton: "Reset two-factor authentication",
    saving: "Saving…",
    saved: "Saved.",
  },
  payments: {
    cardTitle: "Make a payment",
    cardBody: "Pay an invoice or deposit online.",
    payButton: "Pay now",
    // Only the trailing sentence -- Dashboard.tsx's JSX already renders "I
    // have read and agree to the [Terms & Conditions link] and [Privacy
    // Policy link], including the payment, refund, and dispute policies."
    // directly (real links can't live in a plain string constant); this
    // used to duplicate that entire sentence a second time in plain text
    // right after it.
    termsAgreeLabel: "This is required before paying.",
    termsWarning: "Please check the box above to agree to our Terms & Conditions before paying.",
  },
} as const;

export type Strings = typeof strings;
